Ready for Review
maelfosso/microverse_library pull request #1
Opened 2019-10-11 23:27 UTC by maelfosso

Hello,

First, sorry for the message **Can't automatically merge**. I started working on the project alone by waiting for a new partner and when they notify me that there is not yet a partner I typed a few Git commands to arrange everything according to Microverse Guidelines. 
After the review, I will merge and solve the conflicts.

Please, could review my project ?
Thanks.

2019-10-12 20:58 UTC, JamesOkunlade requested changes
### Nice job with the library project 👏 😄 , However, you'll have to set the project up again to avoid the merge conflict and make you stickler work.

When submitting for another review, ensure to add a descriptive README.md file to your project and remove all commented code.

**Status: `Changes required`**

Happy coding! 😎

2019-10-12 20:58 UTC, JamesOkunlade commented on js/app.js
> +
Remove commented code.

2019-10-12 20:58 UTC, JamesOkunlade commented on js/app.js
> +  // document.getElementById("myForm").reset();
Remove commented code.

2019-10-12 20:58 UTC, JamesOkunlade commented on js/app.js
> +// });
Remove commented code

2019-10-13 17:36 UTC, AdnanAfsari approved these changes
Hello @maelfosso ✋ 

Nice, I think you have made all the changes the previous reviewer requested so its 👍 from me.

**Status:Approved**

Happy Coding

2019-10-13 22:47 UTC, merged